apiVersion: v1
kind: Service
metadata:
  namespace: m3demo
  name: uidapp
  labels:
    app: uidapp
spec:
  type: ClusterIP
  ports:
    - name: tcp-40001-40001
      port: 40001
      protocol: TCP
      targetPort: 40001
    - name: tcp-40002-40002
      port: 40002
      protocol: TCP
      targetPort: 40002
    - name: tcp-40003-40003
      port: 40003
      protocol: TCP
      targetPort: 40003
  selector:
    app: uidapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: uidapp
  name: uidapp
  namespace: m3demo
spec:
  serviceName: ""
  replicas: 1
  selector:
    matchLabels:
      app: uidapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uidapp
    spec:
      containers:
        - image: {{ .Values.m3demoimage }}
          imagePullPolicy: Always
          name: uidapp
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          workingDir: /go/bin/demo/deploy
          volumeMounts:
          - name: log
            mountPath: /var/log/m3demo
          - name: m3demo-conf
            mountPath: /go/bin/demo/deploy/configtemp/
          command: [ "/bin/sh", "-c", "touch /var/log/m3demo/app.log;cp configtemp config -rf;sh start.sh k8s world1 uid $(ENV_M3DEMO_Ins)" ]
          env:
            - name: ENV_M3DEMO_Ins
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENV_M3DEMO_Transport_Host
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV_M3DEMO_Transport_Host
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV_M3DEMO_Router_Consul_Consul_Host
              value: consul:8500
            - name: ENV_M3DEMO_Broker_Nats_URL
              value: nats:4222
            - name: ENV_M3DEMO_DB_Mongo_DB
              value: mongodb://mongo:27017
            - name: ENV_M3DEMO_Lease_Etcd_Endpoints
              value: etcd:2379
            - name: ENV_M3DEMO_Trace_Jaeger_Host
              value: jaeger-agent
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.12.0
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
          - mountPath: /var/log/m3demo
            name: log
          - name: filebeat-conf
            mountPath: /etc/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
      restartPolicy: Always
      volumes:
      - name: log 
        emptyDir: {}
      - name: m3demo-conf
        configMap:
          defaultMode: 0640
          name: m3demo-conf
      - name: filebeat-conf
        configMap:
          defaultMode: 0640
          name: filebeat-config-to-logstash