[Transport]
Addr = "127.0.0.1:22103"
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
URL = "127.0.0.1:4222"

[[Plugin.Shape.shape_sentinel]]
ConfigFile = "../../resource/sentinel.yml"

[[Plugin.DB.db_cache]]
Pass = "1"

[[Plugin.Lease.lease_etcd]]
Endpoints = "127.0.0.1:2379"
DialTimeout = 5
LeaseKeepLiveTime = 10
PreExitTime = 5

[Server]
[[Server.Actor]]
ActiveTimeOut = 60  # role 存活时间
SaveTimeInter = 10  # role自动存储时间
TickTimeInter = 10  # 定时器轮转时间
MaxReqChanSize = 10 # 最大接受信道
MaxReqWaitTime = 30 # 最大等待时间
AutoCreate = 1 # 自动创建Actor
LeaseMode = 1   # 启用租约管理
LeasePrefix = "actor"   # 租约前缀
AllocLeaseTimeOut = 10    # 申请租约超时时间
WaitFreeLeaseTimeOut = 3  # 预估数据迁出时长

[App]
PrePareTime = 10 # 启动前准备时长