[Transport]
Addr = "127.0.0.1:22100"
BroadTimeOut = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
NatsURL = "127.0.0.1:4222"

[[Plugin.Shape.shape_sentinel]]
ConfigFile = "../../resource/sentinel.yml"

[[Plugin.Gate.gate_grpc]]
Addr = "127.0.0.1:22000"

[[Plugin.Metric.metric_prom]]
Port = 32100

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

