[Transport]
Addr = "9.135.72.251:22100"
BroadTimeOut = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "9.135.72.251:8500"

[[Plugin.Broker.broker_nats]]
NatsURL = "9.135.72.251:4222"

[[Plugin.Shape.shape_sentinel]]
ConfigFile = "../../resource/sentinel.yml"

[[Plugin.Trace.trace_stdout]]
Pass = ""

[[Plugin.Metric.metric_prom]]
Port = 32100

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.Agent.agent_http]]
Port = 22002
LogicUrl = "/example/logic"
AuthUrl = "/example/auth"
SessionLiveS = 3600

[App]
GatePort = 22001
