[Transport]
Addr = "9.135.72.251:22101"
BroadTimeOut = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "9.135.72.251:8500"

[[Plugin.Broker.broker_nats]]
NatsURL = "9.135.72.251:4222"

[[Plugin.Shape.shape_sentinel]]
ConfigFile = "../../resource/sentinel.yml"

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"
