[Transport]
Addr = "9.135.72.251:22105"
BroadTimeOut = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "9.135.72.251:8500"

[[Plugin.Broker.broker_nats]]
NatsURL = "9.135.72.251:4222"

[App]
PrePareTime = 10 # 启动前准备时长