[Transport]
Addr = "127.0.0.1:22105"
BroadTimeOut = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
NatsURL = "127.0.0.1:4222"
