[Transport]
Host = "127.0.0.1"
Port = 22105
BroadcastTimeout = 5
CloseBroker = 1 # 关闭Broker

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[App]
PrePareTime = 10 # 启动前准备时长
