// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.2.0
// source: gatep.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	metapb "m3game/meta/metapb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CSMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string         `protobuf:"bytes,1,opt,name=Method,proto3" json:"Method,omitempty"`
	Metas   []*metapb.Meta `protobuf:"bytes,2,rep,name=Metas,proto3" json:"Metas,omitempty"`
	Content []byte         `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *CSMsg) Reset() {
	*x = CSMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatep_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSMsg) ProtoMessage() {}

func (x *CSMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gatep_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSMsg.ProtoReflect.Descriptor instead.
func (*CSMsg) Descriptor() ([]byte, []int) {
	return file_gatep_proto_rawDescGZIP(), []int{0}
}

func (x *CSMsg) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CSMsg) GetMetas() []*metapb.Meta {
	if x != nil {
		return x.Metas
	}
	return nil
}

func (x *CSMsg) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_gatep_proto protoreflect.FileDescriptor

var file_gatep_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x05, 0x43, 0x53, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x05, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x42, 0x15, 0x5a, 0x13, 0x6d, 0x33, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gatep_proto_rawDescOnce sync.Once
	file_gatep_proto_rawDescData = file_gatep_proto_rawDesc
)

func file_gatep_proto_rawDescGZIP() []byte {
	file_gatep_proto_rawDescOnce.Do(func() {
		file_gatep_proto_rawDescData = protoimpl.X.CompressGZIP(file_gatep_proto_rawDescData)
	})
	return file_gatep_proto_rawDescData
}

var file_gatep_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gatep_proto_goTypes = []interface{}{
	(*CSMsg)(nil),       // 0: proto.CSMsg
	(*metapb.Meta)(nil), // 1: proto.Meta
}
var file_gatep_proto_depIdxs = []int32{
	1, // 0: proto.CSMsg.Metas:type_name -> proto.Meta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gatep_proto_init() }
func file_gatep_proto_init() {
	if File_gatep_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gatep_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gatep_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gatep_proto_goTypes,
		DependencyIndexes: file_gatep_proto_depIdxs,
		MessageInfos:      file_gatep_proto_msgTypes,
	}.Build()
	File_gatep_proto = out.File
	file_gatep_proto_rawDesc = nil
	file_gatep_proto_goTypes = nil
	file_gatep_proto_depIdxs = nil
}
