// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.2.0
// source: actor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "m3game/meta/metapb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID   string     `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
	ActorName *ActorName `protobuf:"bytes,2,opt,name=ActorName,proto3" json:"ActorName,omitempty"`
	ActorInfo *ActorInfo `protobuf:"bytes,3,opt,name=ActorInfo,proto3" json:"ActorInfo,omitempty"`
}

func (x *ActorDB) Reset() {
	*x = ActorDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDB) ProtoMessage() {}

func (x *ActorDB) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDB.ProtoReflect.Descriptor instead.
func (*ActorDB) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{0}
}

func (x *ActorDB) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

func (x *ActorDB) GetActorName() *ActorName {
	if x != nil {
		return x.ActorName
	}
	return nil
}

func (x *ActorDB) GetActorInfo() *ActorInfo {
	if x != nil {
		return x.ActorInfo
	}
	return nil
}

type ActorName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ActorName) Reset() {
	*x = ActorName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorName) ProtoMessage() {}

func (x *ActorName) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorName.ProtoReflect.Descriptor instead.
func (*ActorName) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{1}
}

func (x *ActorName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ActorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level int32 `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"`
}

func (x *ActorInfo) Reset() {
	*x = ActorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorInfo) ProtoMessage() {}

func (x *ActorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorInfo.ProtoReflect.Descriptor instead.
func (*ActorInfo) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{2}
}

func (x *ActorInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{3}
}

type Kick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Kick) Reset() {
	*x = Kick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{4}
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{5}
}

type ModifyName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModifyName) Reset() {
	*x = ModifyName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyName) ProtoMessage() {}

func (x *ModifyName) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyName.ProtoReflect.Descriptor instead.
func (*ModifyName) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{6}
}

type LvUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LvUp) Reset() {
	*x = LvUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LvUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LvUp) ProtoMessage() {}

func (x *LvUp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LvUp.ProtoReflect.Descriptor instead.
func (*LvUp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{7}
}

type GetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetInfo) Reset() {
	*x = GetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo) ProtoMessage() {}

func (x *GetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo.ProtoReflect.Descriptor instead.
func (*GetInfo) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{8}
}

type PostChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostChannel) Reset() {
	*x = PostChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostChannel) ProtoMessage() {}

func (x *PostChannel) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostChannel.ProtoReflect.Descriptor instead.
func (*PostChannel) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{9}
}

type PullChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullChannel) Reset() {
	*x = PullChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullChannel) ProtoMessage() {}

func (x *PullChannel) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullChannel.ProtoReflect.Descriptor instead.
func (*PullChannel) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{10}
}

type Register_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	PlayerID string `protobuf:"bytes,2,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
}

func (x *Register_Req) Reset() {
	*x = Register_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register_Req) ProtoMessage() {}

func (x *Register_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register_Req.ProtoReflect.Descriptor instead.
func (*Register_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Register_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Register_Req) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

type Register_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Register_Rsp) Reset() {
	*x = Register_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register_Rsp) ProtoMessage() {}

func (x *Register_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register_Rsp.ProtoReflect.Descriptor instead.
func (*Register_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{3, 1}
}

type Kick_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leaseid string `protobuf:"bytes,1,opt,name=leaseid,proto3" json:"leaseid,omitempty"`
}

func (x *Kick_Req) Reset() {
	*x = Kick_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kick_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick_Req) ProtoMessage() {}

func (x *Kick_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick_Req.ProtoReflect.Descriptor instead.
func (*Kick_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Kick_Req) GetLeaseid() string {
	if x != nil {
		return x.Leaseid
	}
	return ""
}

type Kick_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Kick_Rsp) Reset() {
	*x = Kick_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kick_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick_Rsp) ProtoMessage() {}

func (x *Kick_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick_Rsp.ProtoReflect.Descriptor instead.
func (*Kick_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{4, 1}
}

type Login_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID string `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
}

func (x *Login_Req) Reset() {
	*x = Login_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Req) ProtoMessage() {}

func (x *Login_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Req.ProtoReflect.Descriptor instead.
func (*Login_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Login_Req) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

type Login_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorDB *ActorDB `protobuf:"bytes,1,opt,name=ActorDB,proto3" json:"ActorDB,omitempty"`
}

func (x *Login_Rsp) Reset() {
	*x = Login_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Rsp) ProtoMessage() {}

func (x *Login_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Rsp.ProtoReflect.Descriptor instead.
func (*Login_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Login_Rsp) GetActorDB() *ActorDB {
	if x != nil {
		return x.ActorDB
	}
	return nil
}

type ModifyName_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID string `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
	NewName string `protobuf:"bytes,2,opt,name=NewName,proto3" json:"NewName,omitempty"`
}

func (x *ModifyName_Req) Reset() {
	*x = ModifyName_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyName_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyName_Req) ProtoMessage() {}

func (x *ModifyName_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyName_Req.ProtoReflect.Descriptor instead.
func (*ModifyName_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ModifyName_Req) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

func (x *ModifyName_Req) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type ModifyName_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorName *ActorName `protobuf:"bytes,1,opt,name=ActorName,proto3" json:"ActorName,omitempty"`
}

func (x *ModifyName_Rsp) Reset() {
	*x = ModifyName_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyName_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyName_Rsp) ProtoMessage() {}

func (x *ModifyName_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyName_Rsp.ProtoReflect.Descriptor instead.
func (*ModifyName_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{6, 1}
}

func (x *ModifyName_Rsp) GetActorName() *ActorName {
	if x != nil {
		return x.ActorName
	}
	return nil
}

type LvUp_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID string `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
}

func (x *LvUp_Req) Reset() {
	*x = LvUp_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LvUp_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LvUp_Req) ProtoMessage() {}

func (x *LvUp_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LvUp_Req.ProtoReflect.Descriptor instead.
func (*LvUp_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{7, 0}
}

func (x *LvUp_Req) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

type LvUp_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorInfo *ActorInfo `protobuf:"bytes,1,opt,name=ActorInfo,proto3" json:"ActorInfo,omitempty"`
}

func (x *LvUp_Rsp) Reset() {
	*x = LvUp_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LvUp_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LvUp_Rsp) ProtoMessage() {}

func (x *LvUp_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LvUp_Rsp.ProtoReflect.Descriptor instead.
func (*LvUp_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{7, 1}
}

func (x *LvUp_Rsp) GetActorInfo() *ActorInfo {
	if x != nil {
		return x.ActorInfo
	}
	return nil
}

type GetInfo_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID string `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
}

func (x *GetInfo_Req) Reset() {
	*x = GetInfo_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfo_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo_Req) ProtoMessage() {}

func (x *GetInfo_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo_Req.ProtoReflect.Descriptor instead.
func (*GetInfo_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetInfo_Req) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

type GetInfo_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *GetInfo_Rsp) Reset() {
	*x = GetInfo_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfo_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo_Rsp) ProtoMessage() {}

func (x *GetInfo_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo_Rsp.ProtoReflect.Descriptor instead.
func (*GetInfo_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{8, 1}
}

func (x *GetInfo_Rsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfo_Rsp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type PostChannel_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID string `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *PostChannel_Req) Reset() {
	*x = PostChannel_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostChannel_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostChannel_Req) ProtoMessage() {}

func (x *PostChannel_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostChannel_Req.ProtoReflect.Descriptor instead.
func (*PostChannel_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{9, 0}
}

func (x *PostChannel_Req) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

func (x *PostChannel_Req) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostChannel_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass string `protobuf:"bytes,1,opt,name=Pass,proto3" json:"Pass,omitempty"`
}

func (x *PostChannel_Rsp) Reset() {
	*x = PostChannel_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostChannel_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostChannel_Rsp) ProtoMessage() {}

func (x *PostChannel_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostChannel_Rsp.ProtoReflect.Descriptor instead.
func (*PostChannel_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{9, 1}
}

func (x *PostChannel_Rsp) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type PullChannel_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID string `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
}

func (x *PullChannel_Req) Reset() {
	*x = PullChannel_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullChannel_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullChannel_Req) ProtoMessage() {}

func (x *PullChannel_Req) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullChannel_Req.ProtoReflect.Descriptor instead.
func (*PullChannel_Req) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{10, 0}
}

func (x *PullChannel_Req) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

type PullChannel_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*ChannelMsg `protobuf:"bytes,1,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
}

func (x *PullChannel_Rsp) Reset() {
	*x = PullChannel_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actor_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullChannel_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullChannel_Rsp) ProtoMessage() {}

func (x *PullChannel_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullChannel_Rsp.ProtoReflect.Descriptor instead.
func (*PullChannel_Rsp) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{10, 1}
}

func (x *PullChannel_Rsp) GetMsgs() []*ChannelMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

var File_actor_proto protoreflect.FileDescriptor

var file_actor_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x90, 0x01, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x42, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x3a, 0x0b, 0x8a, 0xb5, 0x18, 0x07, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x49, 0x44, 0x22, 0x1f, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x56, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x1a, 0x35, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x73,
	0x70, 0x3a, 0x0c, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22,
	0x36, 0x0a, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x1a, 0x1f, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x69, 0x64, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x3a,
	0x06, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00, 0x22, 0x67, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x1a, 0x1f, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49,
	0x44, 0x1a, 0x2f, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x44, 0x42, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x42, 0x52, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x44, 0x42, 0x3a, 0x0c, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01,
	0x22, 0x8c, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a,
	0x39, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x35, 0x0a, 0x03, 0x52, 0x73,
	0x70, 0x12, 0x2e, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x3a, 0x0c, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22,
	0x6c, 0x0a, 0x04, 0x4c, 0x76, 0x55, 0x70, 0x1a, 0x1f, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x1a, 0x35, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12,
	0x2e, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x3a,
	0x0c, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x69, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x1f, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x1a, 0x2f, 0x0a, 0x03, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x3a, 0x0c, 0xca, 0xf3, 0x18, 0x02,
	0x0a, 0x00, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x71, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x39, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x1a, 0x19, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x73, 0x73, 0x3a, 0x0c, 0xca,
	0xf3, 0x18, 0x02, 0x0a, 0x00, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x6a, 0x0a, 0x0b, 0x50,
	0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x1f, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x1a, 0x2c, 0x0a, 0x03, 0x52,
	0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x4d, 0x73, 0x67, 0x52, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x3a, 0x0c, 0xca, 0xf3, 0x18, 0x02, 0x0a,
	0x00, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x32, 0xce, 0x02, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x73,
	0x70, 0x12, 0x31, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x52, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x73, 0x70,
	0x12, 0x28, 0x0a, 0x04, 0x4c, 0x76, 0x55, 0x70, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x76, 0x55, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x76, 0x55, 0x70, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0b, 0x50, 0x6f,
	0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0b, 0x50, 0x75, 0x6c,
	0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x73, 0x70, 0x32, 0x6d, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x67, 0x53, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a,
	0x04, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x69,
	0x63, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b,
	0x69, 0x63, 0x6b, 0x2e, 0x52, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_actor_proto_rawDescOnce sync.Once
	file_actor_proto_rawDescData = file_actor_proto_rawDesc
)

func file_actor_proto_rawDescGZIP() []byte {
	file_actor_proto_rawDescOnce.Do(func() {
		file_actor_proto_rawDescData = protoimpl.X.CompressGZIP(file_actor_proto_rawDescData)
	})
	return file_actor_proto_rawDescData
}

var file_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_actor_proto_goTypes = []interface{}{
	(*ActorDB)(nil),         // 0: proto.ActorDB
	(*ActorName)(nil),       // 1: proto.ActorName
	(*ActorInfo)(nil),       // 2: proto.ActorInfo
	(*Register)(nil),        // 3: proto.Register
	(*Kick)(nil),            // 4: proto.Kick
	(*Login)(nil),           // 5: proto.Login
	(*ModifyName)(nil),      // 6: proto.ModifyName
	(*LvUp)(nil),            // 7: proto.LvUp
	(*GetInfo)(nil),         // 8: proto.GetInfo
	(*PostChannel)(nil),     // 9: proto.PostChannel
	(*PullChannel)(nil),     // 10: proto.PullChannel
	(*Register_Req)(nil),    // 11: proto.Register.Req
	(*Register_Rsp)(nil),    // 12: proto.Register.Rsp
	(*Kick_Req)(nil),        // 13: proto.Kick.Req
	(*Kick_Rsp)(nil),        // 14: proto.Kick.Rsp
	(*Login_Req)(nil),       // 15: proto.Login.Req
	(*Login_Rsp)(nil),       // 16: proto.Login.Rsp
	(*ModifyName_Req)(nil),  // 17: proto.ModifyName.Req
	(*ModifyName_Rsp)(nil),  // 18: proto.ModifyName.Rsp
	(*LvUp_Req)(nil),        // 19: proto.LvUp.Req
	(*LvUp_Rsp)(nil),        // 20: proto.LvUp.Rsp
	(*GetInfo_Req)(nil),     // 21: proto.GetInfo.Req
	(*GetInfo_Rsp)(nil),     // 22: proto.GetInfo.Rsp
	(*PostChannel_Req)(nil), // 23: proto.PostChannel.Req
	(*PostChannel_Rsp)(nil), // 24: proto.PostChannel.Rsp
	(*PullChannel_Req)(nil), // 25: proto.PullChannel.Req
	(*PullChannel_Rsp)(nil), // 26: proto.PullChannel.Rsp
	(*ChannelMsg)(nil),      // 27: proto.ChannelMsg
}
var file_actor_proto_depIdxs = []int32{
	1,  // 0: proto.ActorDB.ActorName:type_name -> proto.ActorName
	2,  // 1: proto.ActorDB.ActorInfo:type_name -> proto.ActorInfo
	0,  // 2: proto.Login.Rsp.ActorDB:type_name -> proto.ActorDB
	1,  // 3: proto.ModifyName.Rsp.ActorName:type_name -> proto.ActorName
	2,  // 4: proto.LvUp.Rsp.ActorInfo:type_name -> proto.ActorInfo
	27, // 5: proto.PullChannel.Rsp.Msgs:type_name -> proto.ChannelMsg
	15, // 6: proto.ActorSer.Login:input_type -> proto.Login.Req
	21, // 7: proto.ActorSer.GetInfo:input_type -> proto.GetInfo.Req
	17, // 8: proto.ActorSer.ModifyName:input_type -> proto.ModifyName.Req
	19, // 9: proto.ActorSer.LvUp:input_type -> proto.LvUp.Req
	23, // 10: proto.ActorSer.PostChannel:input_type -> proto.PostChannel.Req
	25, // 11: proto.ActorSer.PullChannel:input_type -> proto.PullChannel.Req
	11, // 12: proto.ActorRegSer.Register:input_type -> proto.Register.Req
	13, // 13: proto.ActorRegSer.Kick:input_type -> proto.Kick.Req
	16, // 14: proto.ActorSer.Login:output_type -> proto.Login.Rsp
	22, // 15: proto.ActorSer.GetInfo:output_type -> proto.GetInfo.Rsp
	18, // 16: proto.ActorSer.ModifyName:output_type -> proto.ModifyName.Rsp
	20, // 17: proto.ActorSer.LvUp:output_type -> proto.LvUp.Rsp
	24, // 18: proto.ActorSer.PostChannel:output_type -> proto.PostChannel.Rsp
	26, // 19: proto.ActorSer.PullChannel:output_type -> proto.PullChannel.Rsp
	12, // 20: proto.ActorRegSer.Register:output_type -> proto.Register.Rsp
	14, // 21: proto.ActorRegSer.Kick:output_type -> proto.Kick.Rsp
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_actor_proto_init() }
func file_actor_proto_init() {
	if File_actor_proto != nil {
		return
	}
	file_async_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_actor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LvUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kick_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kick_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyName_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyName_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LvUp_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LvUp_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfo_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfo_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostChannel_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostChannel_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullChannel_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actor_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullChannel_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_actor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_actor_proto_goTypes,
		DependencyIndexes: file_actor_proto_depIdxs,
		MessageInfos:      file_actor_proto_msgTypes,
	}.Build()
	File_actor_proto = out.File
	file_actor_proto_rawDesc = nil
	file_actor_proto_goTypes = nil
	file_actor_proto_depIdxs = nil
}
