// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.2.0
// source: mutil.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb "m3game/proto/pb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{0}
}

type TraceHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TraceHello) Reset() {
	*x = TraceHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceHello) ProtoMessage() {}

func (x *TraceHello) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceHello.ProtoReflect.Descriptor instead.
func (*TraceHello) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{1}
}

type BreakHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BreakHello) Reset() {
	*x = BreakHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakHello) ProtoMessage() {}

func (x *BreakHello) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakHello.ProtoReflect.Descriptor instead.
func (*BreakHello) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{2}
}

type Hello_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Req       string        `protobuf:"bytes,2,opt,name=Req,proto3" json:"Req,omitempty"`
}

func (x *Hello_Req) Reset() {
	*x = Hello_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello_Req) ProtoMessage() {}

func (x *Hello_Req) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello_Req.ProtoReflect.Descriptor instead.
func (*Hello_Req) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Hello_Req) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *Hello_Req) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type Hello_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Rsp       string        `protobuf:"bytes,2,opt,name=Rsp,proto3" json:"Rsp,omitempty"`
}

func (x *Hello_Rsp) Reset() {
	*x = Hello_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello_Rsp) ProtoMessage() {}

func (x *Hello_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello_Rsp.ProtoReflect.Descriptor instead.
func (*Hello_Rsp) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Hello_Rsp) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *Hello_Rsp) GetRsp() string {
	if x != nil {
		return x.Rsp
	}
	return ""
}

type TraceHello_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Req       string        `protobuf:"bytes,2,opt,name=Req,proto3" json:"Req,omitempty"`
}

func (x *TraceHello_Req) Reset() {
	*x = TraceHello_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceHello_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceHello_Req) ProtoMessage() {}

func (x *TraceHello_Req) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceHello_Req.ProtoReflect.Descriptor instead.
func (*TraceHello_Req) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TraceHello_Req) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *TraceHello_Req) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type TraceHello_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Rsp       string        `protobuf:"bytes,2,opt,name=Rsp,proto3" json:"Rsp,omitempty"`
}

func (x *TraceHello_Rsp) Reset() {
	*x = TraceHello_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceHello_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceHello_Rsp) ProtoMessage() {}

func (x *TraceHello_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceHello_Rsp.ProtoReflect.Descriptor instead.
func (*TraceHello_Rsp) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{1, 1}
}

func (x *TraceHello_Rsp) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *TraceHello_Rsp) GetRsp() string {
	if x != nil {
		return x.Rsp
	}
	return ""
}

type BreakHello_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Req       string        `protobuf:"bytes,2,opt,name=Req,proto3" json:"Req,omitempty"`
}

func (x *BreakHello_Req) Reset() {
	*x = BreakHello_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakHello_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakHello_Req) ProtoMessage() {}

func (x *BreakHello_Req) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakHello_Req.ProtoReflect.Descriptor instead.
func (*BreakHello_Req) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BreakHello_Req) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *BreakHello_Req) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type BreakHello_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Rsp       string        `protobuf:"bytes,2,opt,name=Rsp,proto3" json:"Rsp,omitempty"`
}

func (x *BreakHello_Rsp) Reset() {
	*x = BreakHello_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mutil_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreakHello_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakHello_Rsp) ProtoMessage() {}

func (x *BreakHello_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_mutil_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakHello_Rsp.ProtoReflect.Descriptor instead.
func (*BreakHello_Rsp) Descriptor() ([]byte, []int) {
	return file_mutil_proto_rawDescGZIP(), []int{2, 1}
}

func (x *BreakHello_Rsp) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *BreakHello_Rsp) GetRsp() string {
	if x != nil {
		return x.Rsp
	}
	return ""
}

var File_mutil_proto protoreflect.FileDescriptor

var file_mutil_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a,
	0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x47, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a,
	0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x52, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x65, 0x71, 0x1a,
	0x47, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x73, 0x70, 0x3a, 0x06, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00,
	0x22, 0xac, 0x01, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x63, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a,
	0x47, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x65, 0x71, 0x1a, 0x47, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12,
	0x2e, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x73,
	0x70, 0x3a, 0x0c, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00, 0xca, 0xf3, 0x18, 0x02, 0x18, 0x01, 0x22,
	0xa6, 0x01, 0x0a, 0x0a, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x47,
	0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x52, 0x65, 0x71, 0x1a, 0x47, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x2e,
	0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x73, 0x70,
	0x3a, 0x06, 0xca, 0xf3, 0x18, 0x02, 0x0a, 0x00, 0x32, 0xae, 0x02, 0x0a, 0x08, 0x4d, 0x75, 0x74,
	0x69, 0x6c, 0x53, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52,
	0x73, 0x70, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x22, 0x1a, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x65, 0x72,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x3a, 0x01, 0x2a, 0x12, 0x66, 0x0a, 0x0a, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x2e, 0x52, 0x73, 0x70, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x22, 0x1f, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6d, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x3a, 0x01,
	0x2a, 0x12, 0x66, 0x0a, 0x0a, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x72, 0x65, 0x61, 0x6b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52, 0x73, 0x70, 0x22, 0x2a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x24, 0x22, 0x1f, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x6d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x65, 0x72, 0x2f, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x3a, 0x01, 0x2a, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mutil_proto_rawDescOnce sync.Once
	file_mutil_proto_rawDescData = file_mutil_proto_rawDesc
)

func file_mutil_proto_rawDescGZIP() []byte {
	file_mutil_proto_rawDescOnce.Do(func() {
		file_mutil_proto_rawDescData = protoimpl.X.CompressGZIP(file_mutil_proto_rawDescData)
	})
	return file_mutil_proto_rawDescData
}

var file_mutil_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mutil_proto_goTypes = []interface{}{
	(*Hello)(nil),          // 0: proto.Hello
	(*TraceHello)(nil),     // 1: proto.TraceHello
	(*BreakHello)(nil),     // 2: proto.BreakHello
	(*Hello_Req)(nil),      // 3: proto.Hello.Req
	(*Hello_Rsp)(nil),      // 4: proto.Hello.Rsp
	(*TraceHello_Req)(nil), // 5: proto.TraceHello.Req
	(*TraceHello_Rsp)(nil), // 6: proto.TraceHello.Rsp
	(*BreakHello_Req)(nil), // 7: proto.BreakHello.Req
	(*BreakHello_Rsp)(nil), // 8: proto.BreakHello.Rsp
	(*pb.RouteHead)(nil),   // 9: proto.RouteHead
}
var file_mutil_proto_depIdxs = []int32{
	9, // 0: proto.Hello.Req.RouteHead:type_name -> proto.RouteHead
	9, // 1: proto.Hello.Rsp.RouteHead:type_name -> proto.RouteHead
	9, // 2: proto.TraceHello.Req.RouteHead:type_name -> proto.RouteHead
	9, // 3: proto.TraceHello.Rsp.RouteHead:type_name -> proto.RouteHead
	9, // 4: proto.BreakHello.Req.RouteHead:type_name -> proto.RouteHead
	9, // 5: proto.BreakHello.Rsp.RouteHead:type_name -> proto.RouteHead
	3, // 6: proto.MutilSer.Hello:input_type -> proto.Hello.Req
	5, // 7: proto.MutilSer.TraceHello:input_type -> proto.TraceHello.Req
	7, // 8: proto.MutilSer.BreakHello:input_type -> proto.BreakHello.Req
	4, // 9: proto.MutilSer.Hello:output_type -> proto.Hello.Rsp
	6, // 10: proto.MutilSer.TraceHello:output_type -> proto.TraceHello.Rsp
	8, // 11: proto.MutilSer.BreakHello:output_type -> proto.BreakHello.Rsp
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mutil_proto_init() }
func file_mutil_proto_init() {
	if File_mutil_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mutil_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceHello_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceHello_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakHello_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mutil_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreakHello_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mutil_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mutil_proto_goTypes,
		DependencyIndexes: file_mutil_proto_depIdxs,
		MessageInfos:      file_mutil_proto_msgTypes,
	}.Build()
	File_mutil_proto = out.File
	file_mutil_proto_rawDesc = nil
	file_mutil_proto_goTypes = nil
	file_mutil_proto_depIdxs = nil
}
