// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.2.0
// source: simple.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SimpleSerClient is the client API for SimpleSer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleSerClient interface {
	HelloWorld(ctx context.Context, in *HelloWorld_Req, opts ...grpc.CallOption) (*HelloWorld_Rsp, error)
}

type simpleSerClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleSerClient(cc grpc.ClientConnInterface) SimpleSerClient {
	return &simpleSerClient{cc}
}

func (c *simpleSerClient) HelloWorld(ctx context.Context, in *HelloWorld_Req, opts ...grpc.CallOption) (*HelloWorld_Rsp, error) {
	out := new(HelloWorld_Rsp)
	err := c.cc.Invoke(ctx, "/proto.SimpleSer/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleSerServer is the server API for SimpleSer service.
// All implementations must embed UnimplementedSimpleSerServer
// for forward compatibility
type SimpleSerServer interface {
	HelloWorld(context.Context, *HelloWorld_Req) (*HelloWorld_Rsp, error)
	mustEmbedUnimplementedSimpleSerServer()
}

// UnimplementedSimpleSerServer must be embedded to have forward compatible implementations.
type UnimplementedSimpleSerServer struct {
}

func (UnimplementedSimpleSerServer) HelloWorld(context.Context, *HelloWorld_Req) (*HelloWorld_Rsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}
func (UnimplementedSimpleSerServer) mustEmbedUnimplementedSimpleSerServer() {}

// UnsafeSimpleSerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleSerServer will
// result in compilation errors.
type UnsafeSimpleSerServer interface {
	mustEmbedUnimplementedSimpleSerServer()
}

func RegisterSimpleSerServer(s grpc.ServiceRegistrar, srv SimpleSerServer) {
	s.RegisterService(&SimpleSer_ServiceDesc, srv)
}

func _SimpleSer_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorld_Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleSerServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SimpleSer/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleSerServer).HelloWorld(ctx, req.(*HelloWorld_Req))
	}
	return interceptor(ctx, in, info, handler)
}

// SimpleSer_ServiceDesc is the grpc.ServiceDesc for SimpleSer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleSer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SimpleSer",
	HandlerType: (*SimpleSerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _SimpleSer_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simple.proto",
}
