// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: world.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "m3game/meta/metapb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	SrcPos   *Position `protobuf:"bytes,2,opt,name=SrcPos,proto3" json:"SrcPos,omitempty"`      // 出发地
	DstPos   *Position `protobuf:"bytes,3,opt,name=DstPos,proto3" json:"DstPos,omitempty"`      // 目的地
	CurPos   *Position `protobuf:"bytes,4,opt,name=CurPos,proto3" json:"CurPos,omitempty"`      // 当前位置
	MoveTime int64     `protobuf:"varint,5,opt,name=MoveTime,proto3" json:"MoveTime,omitempty"` // 出发时间
	Moved    int32     `protobuf:"varint,6,opt,name=Moved,proto3" json:"Moved,omitempty"`       // 已经行进路程
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetSrcPos() *Position {
	if x != nil {
		return x.SrcPos
	}
	return nil
}

func (x *Entity) GetDstPos() *Position {
	if x != nil {
		return x.DstPos
	}
	return nil
}

func (x *Entity) GetCurPos() *Position {
	if x != nil {
		return x.CurPos
	}
	return nil
}

func (x *Entity) GetMoveTime() int64 {
	if x != nil {
		return x.MoveTime
	}
	return 0
}

func (x *Entity) GetMoved() int32 {
	if x != nil {
		return x.Moved
	}
	return 0
}

type CreateEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateEntity) Reset() {
	*x = CreateEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntity) ProtoMessage() {}

func (x *CreateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntity.ProtoReflect.Descriptor instead.
func (*CreateEntity) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2}
}

type MoveEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveEntity) Reset() {
	*x = MoveEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEntity) ProtoMessage() {}

func (x *MoveEntity) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEntity.ProtoReflect.Descriptor instead.
func (*MoveEntity) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{3}
}

type ViewEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewEntity) Reset() {
	*x = ViewEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewEntity) ProtoMessage() {}

func (x *ViewEntity) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewEntity.ProtoReflect.Descriptor instead.
func (*ViewEntity) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{4}
}

type ViewPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewPosition) Reset() {
	*x = ViewPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPosition) ProtoMessage() {}

func (x *ViewPosition) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPosition.ProtoReflect.Descriptor instead.
func (*ViewPosition) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{5}
}

type CreateEntity_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	SrcPos *Position `protobuf:"bytes,2,opt,name=SrcPos,proto3" json:"SrcPos,omitempty"`
}

func (x *CreateEntity_Req) Reset() {
	*x = CreateEntity_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEntity_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntity_Req) ProtoMessage() {}

func (x *CreateEntity_Req) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntity_Req.ProtoReflect.Descriptor instead.
func (*CreateEntity_Req) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateEntity_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEntity_Req) GetSrcPos() *Position {
	if x != nil {
		return x.SrcPos
	}
	return nil
}

type CreateEntity_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *Entity `protobuf:"bytes,1,opt,name=Entity,proto3" json:"Entity,omitempty"`
}

func (x *CreateEntity_Rsp) Reset() {
	*x = CreateEntity_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEntity_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntity_Rsp) ProtoMessage() {}

func (x *CreateEntity_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntity_Rsp.ProtoReflect.Descriptor instead.
func (*CreateEntity_Rsp) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CreateEntity_Rsp) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type MoveEntity_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DstPos *Position `protobuf:"bytes,2,opt,name=DstPos,proto3" json:"DstPos,omitempty"`
}

func (x *MoveEntity_Req) Reset() {
	*x = MoveEntity_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveEntity_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEntity_Req) ProtoMessage() {}

func (x *MoveEntity_Req) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEntity_Req.ProtoReflect.Descriptor instead.
func (*MoveEntity_Req) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{3, 0}
}

func (x *MoveEntity_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MoveEntity_Req) GetDstPos() *Position {
	if x != nil {
		return x.DstPos
	}
	return nil
}

type MoveEntity_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *Entity `protobuf:"bytes,1,opt,name=Entity,proto3" json:"Entity,omitempty"`
}

func (x *MoveEntity_Rsp) Reset() {
	*x = MoveEntity_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveEntity_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveEntity_Rsp) ProtoMessage() {}

func (x *MoveEntity_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveEntity_Rsp.ProtoReflect.Descriptor instead.
func (*MoveEntity_Rsp) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{3, 1}
}

func (x *MoveEntity_Rsp) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type ViewEntity_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ViewEntity_Req) Reset() {
	*x = ViewEntity_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewEntity_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewEntity_Req) ProtoMessage() {}

func (x *ViewEntity_Req) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewEntity_Req.ProtoReflect.Descriptor instead.
func (*ViewEntity_Req) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ViewEntity_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ViewEntity_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *Entity `protobuf:"bytes,1,opt,name=Entity,proto3" json:"Entity,omitempty"`
}

func (x *ViewEntity_Rsp) Reset() {
	*x = ViewEntity_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewEntity_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewEntity_Rsp) ProtoMessage() {}

func (x *ViewEntity_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewEntity_Rsp.ProtoReflect.Descriptor instead.
func (*ViewEntity_Rsp) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ViewEntity_Rsp) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type ViewPosition_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos *Position `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
}

func (x *ViewPosition_Req) Reset() {
	*x = ViewPosition_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewPosition_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPosition_Req) ProtoMessage() {}

func (x *ViewPosition_Req) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPosition_Req.ProtoReflect.Descriptor instead.
func (*ViewPosition_Req) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ViewPosition_Req) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type ViewPosition_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entitys []*Entity `protobuf:"bytes,1,rep,name=Entitys,proto3" json:"Entitys,omitempty"`
}

func (x *ViewPosition_Rsp) Reset() {
	*x = ViewPosition_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewPosition_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPosition_Rsp) ProtoMessage() {}

func (x *ViewPosition_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPosition_Rsp.ProtoReflect.Descriptor instead.
func (*ViewPosition_Rsp) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ViewPosition_Rsp) GetEntitys() []*Entity {
	if x != nil {
		return x.Entitys
	}
	return nil
}

var File_world_proto protoreflect.FileDescriptor

var file_world_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a,
	0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x22, 0xc9, 0x01, 0x0a, 0x06,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x53, 0x72,
	0x63, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x53, 0x72, 0x63,
	0x50, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x44, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x44, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x06,
	0x43, 0x75, 0x72, 0x50, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x43,
	0x75, 0x72, 0x50, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x42, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x73, 0x1a, 0x2c, 0x0a, 0x03,
	0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x3a, 0x06, 0xca, 0xf3, 0x18, 0x02,
	0x20, 0x01, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x1a, 0x42, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06,
	0x44, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x44,
	0x73, 0x74, 0x50, 0x6f, 0x73, 0x1a, 0x2c, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x3a, 0x06, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x5d, 0x0a, 0x0a, 0x56,
	0x69, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x19, 0x0a, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x2c, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x3a, 0x06, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x70, 0x0a, 0x0c, 0x56, 0x69,
	0x65, 0x77, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x28, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x12, 0x21, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x03, 0x50, 0x6f, 0x73, 0x1a, 0x2e, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x07, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x07, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x73, 0x3a, 0x06, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x32, 0x86, 0x02, 0x0a,
	0x08, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0a, 0x4d,
	0x6f, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x71,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0a, 0x56, 0x69, 0x65, 0x77, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69,
	0x65, 0x77, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x52, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x0c, 0x56, 0x69, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_world_proto_rawDescOnce sync.Once
	file_world_proto_rawDescData = file_world_proto_rawDesc
)

func file_world_proto_rawDescGZIP() []byte {
	file_world_proto_rawDescOnce.Do(func() {
		file_world_proto_rawDescData = protoimpl.X.CompressGZIP(file_world_proto_rawDescData)
	})
	return file_world_proto_rawDescData
}

var file_world_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_world_proto_goTypes = []interface{}{
	(*Position)(nil),         // 0: proto.Position
	(*Entity)(nil),           // 1: proto.Entity
	(*CreateEntity)(nil),     // 2: proto.CreateEntity
	(*MoveEntity)(nil),       // 3: proto.MoveEntity
	(*ViewEntity)(nil),       // 4: proto.ViewEntity
	(*ViewPosition)(nil),     // 5: proto.ViewPosition
	(*CreateEntity_Req)(nil), // 6: proto.CreateEntity.Req
	(*CreateEntity_Rsp)(nil), // 7: proto.CreateEntity.Rsp
	(*MoveEntity_Req)(nil),   // 8: proto.MoveEntity.Req
	(*MoveEntity_Rsp)(nil),   // 9: proto.MoveEntity.Rsp
	(*ViewEntity_Req)(nil),   // 10: proto.ViewEntity.Req
	(*ViewEntity_Rsp)(nil),   // 11: proto.ViewEntity.Rsp
	(*ViewPosition_Req)(nil), // 12: proto.ViewPosition.Req
	(*ViewPosition_Rsp)(nil), // 13: proto.ViewPosition.Rsp
}
var file_world_proto_depIdxs = []int32{
	0,  // 0: proto.Entity.SrcPos:type_name -> proto.Position
	0,  // 1: proto.Entity.DstPos:type_name -> proto.Position
	0,  // 2: proto.Entity.CurPos:type_name -> proto.Position
	0,  // 3: proto.CreateEntity.Req.SrcPos:type_name -> proto.Position
	1,  // 4: proto.CreateEntity.Rsp.Entity:type_name -> proto.Entity
	0,  // 5: proto.MoveEntity.Req.DstPos:type_name -> proto.Position
	1,  // 6: proto.MoveEntity.Rsp.Entity:type_name -> proto.Entity
	1,  // 7: proto.ViewEntity.Rsp.Entity:type_name -> proto.Entity
	0,  // 8: proto.ViewPosition.Req.Pos:type_name -> proto.Position
	1,  // 9: proto.ViewPosition.Rsp.Entitys:type_name -> proto.Entity
	6,  // 10: proto.WorldSer.CreateEntity:input_type -> proto.CreateEntity.Req
	8,  // 11: proto.WorldSer.MoveEntity:input_type -> proto.MoveEntity.Req
	10, // 12: proto.WorldSer.ViewEntity:input_type -> proto.ViewEntity.Req
	12, // 13: proto.WorldSer.ViewPosition:input_type -> proto.ViewPosition.Req
	7,  // 14: proto.WorldSer.CreateEntity:output_type -> proto.CreateEntity.Rsp
	9,  // 15: proto.WorldSer.MoveEntity:output_type -> proto.MoveEntity.Rsp
	11, // 16: proto.WorldSer.ViewEntity:output_type -> proto.ViewEntity.Rsp
	13, // 17: proto.WorldSer.ViewPosition:output_type -> proto.ViewPosition.Rsp
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_world_proto_init() }
func file_world_proto_init() {
	if File_world_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_world_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEntity_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEntity_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveEntity_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveEntity_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewEntity_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewEntity_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewPosition_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewPosition_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_world_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_world_proto_goTypes,
		DependencyIndexes: file_world_proto_depIdxs,
		MessageInfos:      file_world_proto_msgTypes,
	}.Build()
	File_world_proto = out.File
	file_world_proto_rawDesc = nil
	file_world_proto_goTypes = nil
	file_world_proto_depIdxs = nil
}
