// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: dir.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb "m3game/proto/pb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_dir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_dir_proto_rawDescGZIP(), []int{0}
}

type Hello_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Req       string        `protobuf:"bytes,2,opt,name=Req,proto3" json:"Req,omitempty"`
}

func (x *Hello_Req) Reset() {
	*x = Hello_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello_Req) ProtoMessage() {}

func (x *Hello_Req) ProtoReflect() protoreflect.Message {
	mi := &file_dir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello_Req.ProtoReflect.Descriptor instead.
func (*Hello_Req) Descriptor() ([]byte, []int) {
	return file_dir_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Hello_Req) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *Hello_Req) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type Hello_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Rsp       string        `protobuf:"bytes,2,opt,name=Rsp,proto3" json:"Rsp,omitempty"`
}

func (x *Hello_Rsp) Reset() {
	*x = Hello_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello_Rsp) ProtoMessage() {}

func (x *Hello_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_dir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello_Rsp.ProtoReflect.Descriptor instead.
func (*Hello_Rsp) Descriptor() ([]byte, []int) {
	return file_dir_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Hello_Rsp) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *Hello_Rsp) GetRsp() string {
	if x != nil {
		return x.Rsp
	}
	return ""
}

var File_dir_proto protoreflect.FileDescriptor

var file_dir_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x09, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01,
	0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x47, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x2e,
	0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x65, 0x71,
	0x1a, 0x47, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x73, 0x70, 0x32, 0x35, 0x0a, 0x06, 0x44, 0x69, 0x72,
	0x53, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52, 0x73, 0x70,
	0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dir_proto_rawDescOnce sync.Once
	file_dir_proto_rawDescData = file_dir_proto_rawDesc
)

func file_dir_proto_rawDescGZIP() []byte {
	file_dir_proto_rawDescOnce.Do(func() {
		file_dir_proto_rawDescData = protoimpl.X.CompressGZIP(file_dir_proto_rawDescData)
	})
	return file_dir_proto_rawDescData
}

var file_dir_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dir_proto_goTypes = []interface{}{
	(*Hello)(nil),        // 0: proto.Hello
	(*Hello_Req)(nil),    // 1: proto.Hello.Req
	(*Hello_Rsp)(nil),    // 2: proto.Hello.Rsp
	(*pb.RouteHead)(nil), // 3: proto.RouteHead
}
var file_dir_proto_depIdxs = []int32{
	3, // 0: proto.Hello.Req.RouteHead:type_name -> proto.RouteHead
	3, // 1: proto.Hello.Rsp.RouteHead:type_name -> proto.RouteHead
	1, // 2: proto.DirSer.Hello:input_type -> proto.Hello.Req
	2, // 3: proto.DirSer.Hello:output_type -> proto.Hello.Rsp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dir_proto_init() }
func file_dir_proto_init() {
	if File_dir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dir_proto_goTypes,
		DependencyIndexes: file_dir_proto_depIdxs,
		MessageInfos:      file_dir_proto_msgTypes,
	}.Build()
	File_dir_proto = out.File
	file_dir_proto_rawDesc = nil
	file_dir_proto_goTypes = nil
	file_dir_proto_depIdxs = nil
}
