// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.2.0
// source: dir.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DirSerClient is the client API for DirSer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirSerClient interface {
	Hello(ctx context.Context, in *Hello_Req, opts ...grpc.CallOption) (*Hello_Rsp, error)
}

type dirSerClient struct {
	cc grpc.ClientConnInterface
}

func NewDirSerClient(cc grpc.ClientConnInterface) DirSerClient {
	return &dirSerClient{cc}
}

func (c *dirSerClient) Hello(ctx context.Context, in *Hello_Req, opts ...grpc.CallOption) (*Hello_Rsp, error) {
	out := new(Hello_Rsp)
	err := c.cc.Invoke(ctx, "/proto.DirSer/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirSerServer is the server API for DirSer service.
// All implementations must embed UnimplementedDirSerServer
// for forward compatibility
type DirSerServer interface {
	Hello(context.Context, *Hello_Req) (*Hello_Rsp, error)
	mustEmbedUnimplementedDirSerServer()
}

// UnimplementedDirSerServer must be embedded to have forward compatible implementations.
type UnimplementedDirSerServer struct {
}

func (UnimplementedDirSerServer) Hello(context.Context, *Hello_Req) (*Hello_Rsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedDirSerServer) mustEmbedUnimplementedDirSerServer() {}

// UnsafeDirSerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirSerServer will
// result in compilation errors.
type UnsafeDirSerServer interface {
	mustEmbedUnimplementedDirSerServer()
}

func RegisterDirSerServer(s grpc.ServiceRegistrar, srv DirSerServer) {
	s.RegisterService(&DirSer_ServiceDesc, srv)
}

func _DirSer_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello_Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirSerServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DirSer/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirSerServer).Hello(ctx, req.(*Hello_Req))
	}
	return interceptor(ctx, in, info, handler)
}

// DirSer_ServiceDesc is the grpc.ServiceDesc for DirSer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirSer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DirSer",
	HandlerType: (*DirSerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _DirSer_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dir.proto",
}
