// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: map.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb "m3game/proto/pb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{0}
}

type Move_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Name      string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Distance  int32         `protobuf:"varint,3,opt,name=Distance,proto3" json:"Distance,omitempty"`
}

func (x *Move_Req) Reset() {
	*x = Move_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move_Req) ProtoMessage() {}

func (x *Move_Req) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move_Req.ProtoReflect.Descriptor instead.
func (*Move_Req) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Move_Req) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *Move_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Move_Req) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type Move_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteHead *pb.RouteHead `protobuf:"bytes,1,opt,name=RouteHead,proto3" json:"RouteHead,omitempty"`
	Name      string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Location  int32         `protobuf:"varint,3,opt,name=Location,proto3" json:"Location,omitempty"`
}

func (x *Move_Rsp) Reset() {
	*x = Move_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move_Rsp) ProtoMessage() {}

func (x *Move_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move_Rsp.ProtoReflect.Descriptor instead.
func (*Move_Rsp) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Move_Rsp) GetRouteHead() *pb.RouteHead {
	if x != nil {
		return x.RouteHead
	}
	return nil
}

func (x *Move_Rsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Move_Rsp) GetLocation() int32 {
	if x != nil {
		return x.Location
	}
	return 0
}

var File_map_proto protoreflect.FileDescriptor

var file_map_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x09, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x01,
	0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x1a, 0x65, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a,
	0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x65, 0x0a,
	0x03, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x32, 0x32, 0x0a, 0x06, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x12, 0x28,
	0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x52, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_map_proto_rawDescOnce sync.Once
	file_map_proto_rawDescData = file_map_proto_rawDesc
)

func file_map_proto_rawDescGZIP() []byte {
	file_map_proto_rawDescOnce.Do(func() {
		file_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_map_proto_rawDescData)
	})
	return file_map_proto_rawDescData
}

var file_map_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_map_proto_goTypes = []interface{}{
	(*Move)(nil),         // 0: proto.Move
	(*Move_Req)(nil),     // 1: proto.Move.Req
	(*Move_Rsp)(nil),     // 2: proto.Move.Rsp
	(*pb.RouteHead)(nil), // 3: proto.RouteHead
}
var file_map_proto_depIdxs = []int32{
	3, // 0: proto.Move.Req.RouteHead:type_name -> proto.RouteHead
	3, // 1: proto.Move.Rsp.RouteHead:type_name -> proto.RouteHead
	1, // 2: proto.MapSer.Move:input_type -> proto.Move.Req
	2, // 3: proto.MapSer.Move:output_type -> proto.Move.Rsp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_map_proto_init() }
func file_map_proto_init() {
	if File_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_map_proto_goTypes,
		DependencyIndexes: file_map_proto_depIdxs,
		MessageInfos:      file_map_proto_msgTypes,
	}.Build()
	File_map_proto = out.File
	file_map_proto_rawDesc = nil
	file_map_proto_goTypes = nil
	file_map_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MapSerClient is the client API for MapSer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MapSerClient interface {
	Move(ctx context.Context, in *Move_Req, opts ...grpc.CallOption) (*Move_Rsp, error)
}

type mapSerClient struct {
	cc grpc.ClientConnInterface
}

func NewMapSerClient(cc grpc.ClientConnInterface) MapSerClient {
	return &mapSerClient{cc}
}

func (c *mapSerClient) Move(ctx context.Context, in *Move_Req, opts ...grpc.CallOption) (*Move_Rsp, error) {
	out := new(Move_Rsp)
	err := c.cc.Invoke(ctx, "/proto.MapSer/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapSerServer is the server API for MapSer service.
type MapSerServer interface {
	Move(context.Context, *Move_Req) (*Move_Rsp, error)
}

// UnimplementedMapSerServer can be embedded to have forward compatible implementations.
type UnimplementedMapSerServer struct {
}

func (*UnimplementedMapSerServer) Move(context.Context, *Move_Req) (*Move_Rsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}

func RegisterMapSerServer(s *grpc.Server, srv MapSerServer) {
	s.RegisterService(&_MapSer_serviceDesc, srv)
}

func _MapSer_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Move_Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapSerServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MapSer/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapSerServer).Move(ctx, req.(*Move_Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _MapSer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MapSer",
	HandlerType: (*MapSerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Move",
			Handler:    _MapSer_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "map.proto",
}
