// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.2.0
// source: role.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "m3game/meta/metapb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleLogin) Reset() {
	*x = RoleLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleLogin) ProtoMessage() {}

func (x *RoleLogin) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleLogin.ProtoReflect.Descriptor instead.
func (*RoleLogin) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

type RoleGetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleGetInfo) Reset() {
	*x = RoleGetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetInfo) ProtoMessage() {}

func (x *RoleGetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetInfo.ProtoReflect.Descriptor instead.
func (*RoleGetInfo) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

type RoleModifyName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleModifyName) Reset() {
	*x = RoleModifyName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleModifyName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleModifyName) ProtoMessage() {}

func (x *RoleModifyName) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleModifyName.ProtoReflect.Descriptor instead.
func (*RoleModifyName) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2}
}

type RolePowerUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RolePowerUp) Reset() {
	*x = RolePowerUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePowerUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePowerUp) ProtoMessage() {}

func (x *RolePowerUp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePowerUp.ProtoReflect.Descriptor instead.
func (*RolePowerUp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3}
}

type RolePostChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RolePostChannel) Reset() {
	*x = RolePostChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePostChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePostChannel) ProtoMessage() {}

func (x *RolePostChannel) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePostChannel.ProtoReflect.Descriptor instead.
func (*RolePostChannel) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4}
}

type RoleGetClubRoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleGetClubRoleInfo) Reset() {
	*x = RoleGetClubRoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubRoleInfo) ProtoMessage() {}

func (x *RoleGetClubRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubRoleInfo.ProtoReflect.Descriptor instead.
func (*RoleGetClubRoleInfo) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{5}
}

type RoleGetClubList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleGetClubList) Reset() {
	*x = RoleGetClubList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubList) ProtoMessage() {}

func (x *RoleGetClubList) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubList.ProtoReflect.Descriptor instead.
func (*RoleGetClubList) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{6}
}

type RoleGetClubInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleGetClubInfo) Reset() {
	*x = RoleGetClubInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubInfo) ProtoMessage() {}

func (x *RoleGetClubInfo) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubInfo.ProtoReflect.Descriptor instead.
func (*RoleGetClubInfo) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{7}
}

type RoleCreateClub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleCreateClub) Reset() {
	*x = RoleCreateClub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleCreateClub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateClub) ProtoMessage() {}

func (x *RoleCreateClub) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateClub.ProtoReflect.Descriptor instead.
func (*RoleCreateClub) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{8}
}

type RoleJoinClub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleJoinClub) Reset() {
	*x = RoleJoinClub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleJoinClub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleJoinClub) ProtoMessage() {}

func (x *RoleJoinClub) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleJoinClub.ProtoReflect.Descriptor instead.
func (*RoleJoinClub) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{9}
}

type RoleExitClub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleExitClub) Reset() {
	*x = RoleExitClub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleExitClub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleExitClub) ProtoMessage() {}

func (x *RoleExitClub) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleExitClub.ProtoReflect.Descriptor instead.
func (*RoleExitClub) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{10}
}

type RoleCancelClub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleCancelClub) Reset() {
	*x = RoleCancelClub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleCancelClub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCancelClub) ProtoMessage() {}

func (x *RoleCancelClub) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCancelClub.ProtoReflect.Descriptor instead.
func (*RoleCancelClub) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{11}
}

type RoleRecvChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleRecvChannel) Reset() {
	*x = RoleRecvChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleRecvChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRecvChannel) ProtoMessage() {}

func (x *RoleRecvChannel) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRecvChannel.ProtoReflect.Descriptor instead.
func (*RoleRecvChannel) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{12}
}

type RoleKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleKick) Reset() {
	*x = RoleKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleKick) ProtoMessage() {}

func (x *RoleKick) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleKick.ProtoReflect.Descriptor instead.
func (*RoleKick) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{13}
}

type RoleLogin_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *RoleLogin_Req) Reset() {
	*x = RoleLogin_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleLogin_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleLogin_Req) ProtoMessage() {}

func (x *RoleLogin_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleLogin_Req.ProtoReflect.Descriptor instead.
func (*RoleLogin_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RoleLogin_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type RoleLogin_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleDB     *RoleDB     `protobuf:"bytes,1,opt,name=RoleDB,proto3" json:"RoleDB,omitempty"`
	ClubRoleDB *ClubRoleDB `protobuf:"bytes,2,opt,name=ClubRoleDB,proto3" json:"ClubRoleDB,omitempty"`
}

func (x *RoleLogin_Rsp) Reset() {
	*x = RoleLogin_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleLogin_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleLogin_Rsp) ProtoMessage() {}

func (x *RoleLogin_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleLogin_Rsp.ProtoReflect.Descriptor instead.
func (*RoleLogin_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RoleLogin_Rsp) GetRoleDB() *RoleDB {
	if x != nil {
		return x.RoleDB
	}
	return nil
}

func (x *RoleLogin_Rsp) GetClubRoleDB() *ClubRoleDB {
	if x != nil {
		return x.ClubRoleDB
	}
	return nil
}

type RoleGetInfo_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *RoleGetInfo_Req) Reset() {
	*x = RoleGetInfo_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetInfo_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetInfo_Req) ProtoMessage() {}

func (x *RoleGetInfo_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetInfo_Req.ProtoReflect.Descriptor instead.
func (*RoleGetInfo_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RoleGetInfo_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type RoleGetInfo_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleDB     *RoleDB     `protobuf:"bytes,1,opt,name=RoleDB,proto3" json:"RoleDB,omitempty"`
	ClubRoleDB *ClubRoleDB `protobuf:"bytes,2,opt,name=ClubRoleDB,proto3" json:"ClubRoleDB,omitempty"`
}

func (x *RoleGetInfo_Rsp) Reset() {
	*x = RoleGetInfo_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetInfo_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetInfo_Rsp) ProtoMessage() {}

func (x *RoleGetInfo_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetInfo_Rsp.ProtoReflect.Descriptor instead.
func (*RoleGetInfo_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RoleGetInfo_Rsp) GetRoleDB() *RoleDB {
	if x != nil {
		return x.RoleDB
	}
	return nil
}

func (x *RoleGetInfo_Rsp) GetClubRoleDB() *ClubRoleDB {
	if x != nil {
		return x.ClubRoleDB
	}
	return nil
}

type RoleModifyName_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId  string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	NewName string `protobuf:"bytes,2,opt,name=NewName,proto3" json:"NewName,omitempty"`
}

func (x *RoleModifyName_Req) Reset() {
	*x = RoleModifyName_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleModifyName_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleModifyName_Req) ProtoMessage() {}

func (x *RoleModifyName_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleModifyName_Req.ProtoReflect.Descriptor instead.
func (*RoleModifyName_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RoleModifyName_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleModifyName_Req) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RoleModifyName_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName *RoleName `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
}

func (x *RoleModifyName_Rsp) Reset() {
	*x = RoleModifyName_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleModifyName_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleModifyName_Rsp) ProtoMessage() {}

func (x *RoleModifyName_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleModifyName_Rsp.ProtoReflect.Descriptor instead.
func (*RoleModifyName_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RoleModifyName_Rsp) GetRoleName() *RoleName {
	if x != nil {
		return x.RoleName
	}
	return nil
}

type RolePowerUp_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId  string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	PowerUp int32  `protobuf:"varint,2,opt,name=PowerUp,proto3" json:"PowerUp,omitempty"`
}

func (x *RolePowerUp_Req) Reset() {
	*x = RolePowerUp_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePowerUp_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePowerUp_Req) ProtoMessage() {}

func (x *RolePowerUp_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePowerUp_Req.ProtoReflect.Descriptor instead.
func (*RolePowerUp_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RolePowerUp_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RolePowerUp_Req) GetPowerUp() int32 {
	if x != nil {
		return x.PowerUp
	}
	return 0
}

type RolePowerUp_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RolePower *RolePower `protobuf:"bytes,1,opt,name=RolePower,proto3" json:"RolePower,omitempty"`
}

func (x *RolePowerUp_Rsp) Reset() {
	*x = RolePowerUp_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePowerUp_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePowerUp_Rsp) ProtoMessage() {}

func (x *RolePowerUp_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePowerUp_Rsp.ProtoReflect.Descriptor instead.
func (*RolePowerUp_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3, 1}
}

func (x *RolePowerUp_Rsp) GetRolePower() *RolePower {
	if x != nil {
		return x.RolePower
	}
	return nil
}

type RolePostChannel_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId  string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *RolePostChannel_Req) Reset() {
	*x = RolePostChannel_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePostChannel_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePostChannel_Req) ProtoMessage() {}

func (x *RolePostChannel_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePostChannel_Req.ProtoReflect.Descriptor instead.
func (*RolePostChannel_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4, 0}
}

func (x *RolePostChannel_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RolePostChannel_Req) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RolePostChannel_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RolePostChannel_Rsp) Reset() {
	*x = RolePostChannel_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePostChannel_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePostChannel_Rsp) ProtoMessage() {}

func (x *RolePostChannel_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePostChannel_Rsp.ProtoReflect.Descriptor instead.
func (*RolePostChannel_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4, 1}
}

type RoleGetClubRoleInfo_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *RoleGetClubRoleInfo_Req) Reset() {
	*x = RoleGetClubRoleInfo_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubRoleInfo_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubRoleInfo_Req) ProtoMessage() {}

func (x *RoleGetClubRoleInfo_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubRoleInfo_Req.ProtoReflect.Descriptor instead.
func (*RoleGetClubRoleInfo_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RoleGetClubRoleInfo_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type RoleGetClubRoleInfo_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubRoleDB *ClubRoleDB `protobuf:"bytes,1,opt,name=ClubRoleDB,proto3" json:"ClubRoleDB,omitempty"`
}

func (x *RoleGetClubRoleInfo_Rsp) Reset() {
	*x = RoleGetClubRoleInfo_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubRoleInfo_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubRoleInfo_Rsp) ProtoMessage() {}

func (x *RoleGetClubRoleInfo_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubRoleInfo_Rsp.ProtoReflect.Descriptor instead.
func (*RoleGetClubRoleInfo_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{5, 1}
}

func (x *RoleGetClubRoleInfo_Rsp) GetClubRoleDB() *ClubRoleDB {
	if x != nil {
		return x.ClubRoleDB
	}
	return nil
}

type RoleGetClubList_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *RoleGetClubList_Req) Reset() {
	*x = RoleGetClubList_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubList_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubList_Req) ProtoMessage() {}

func (x *RoleGetClubList_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubList_Req.ProtoReflect.Descriptor instead.
func (*RoleGetClubList_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RoleGetClubList_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type RoleGetClubList_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubDBs []*ClubDB `protobuf:"bytes,1,rep,name=ClubDBs,proto3" json:"ClubDBs,omitempty"`
}

func (x *RoleGetClubList_Rsp) Reset() {
	*x = RoleGetClubList_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubList_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubList_Rsp) ProtoMessage() {}

func (x *RoleGetClubList_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubList_Rsp.ProtoReflect.Descriptor instead.
func (*RoleGetClubList_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{6, 1}
}

func (x *RoleGetClubList_Rsp) GetClubDBs() []*ClubDB {
	if x != nil {
		return x.ClubDBs
	}
	return nil
}

type RoleGetClubInfo_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	ClubId string `protobuf:"bytes,2,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
}

func (x *RoleGetClubInfo_Req) Reset() {
	*x = RoleGetClubInfo_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubInfo_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubInfo_Req) ProtoMessage() {}

func (x *RoleGetClubInfo_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubInfo_Req.ProtoReflect.Descriptor instead.
func (*RoleGetClubInfo_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RoleGetClubInfo_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleGetClubInfo_Req) GetClubId() string {
	if x != nil {
		return x.ClubId
	}
	return ""
}

type RoleGetClubInfo_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubDB *ClubDB `protobuf:"bytes,1,opt,name=ClubDB,proto3" json:"ClubDB,omitempty"`
}

func (x *RoleGetClubInfo_Rsp) Reset() {
	*x = RoleGetClubInfo_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleGetClubInfo_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetClubInfo_Rsp) ProtoMessage() {}

func (x *RoleGetClubInfo_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetClubInfo_Rsp.ProtoReflect.Descriptor instead.
func (*RoleGetClubInfo_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{7, 1}
}

func (x *RoleGetClubInfo_Rsp) GetClubDB() *ClubDB {
	if x != nil {
		return x.ClubDB
	}
	return nil
}

type RoleCreateClub_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *RoleCreateClub_Req) Reset() {
	*x = RoleCreateClub_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleCreateClub_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateClub_Req) ProtoMessage() {}

func (x *RoleCreateClub_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateClub_Req.ProtoReflect.Descriptor instead.
func (*RoleCreateClub_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{8, 0}
}

func (x *RoleCreateClub_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type RoleCreateClub_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubId string `protobuf:"bytes,2,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
}

func (x *RoleCreateClub_Rsp) Reset() {
	*x = RoleCreateClub_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleCreateClub_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCreateClub_Rsp) ProtoMessage() {}

func (x *RoleCreateClub_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCreateClub_Rsp.ProtoReflect.Descriptor instead.
func (*RoleCreateClub_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{8, 1}
}

func (x *RoleCreateClub_Rsp) GetClubId() string {
	if x != nil {
		return x.ClubId
	}
	return ""
}

type RoleJoinClub_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	ClubId string `protobuf:"bytes,2,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
}

func (x *RoleJoinClub_Req) Reset() {
	*x = RoleJoinClub_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleJoinClub_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleJoinClub_Req) ProtoMessage() {}

func (x *RoleJoinClub_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleJoinClub_Req.ProtoReflect.Descriptor instead.
func (*RoleJoinClub_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{9, 0}
}

func (x *RoleJoinClub_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleJoinClub_Req) GetClubId() string {
	if x != nil {
		return x.ClubId
	}
	return ""
}

type RoleJoinClub_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleJoinClub_Rsp) Reset() {
	*x = RoleJoinClub_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleJoinClub_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleJoinClub_Rsp) ProtoMessage() {}

func (x *RoleJoinClub_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleJoinClub_Rsp.ProtoReflect.Descriptor instead.
func (*RoleJoinClub_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{9, 1}
}

type RoleExitClub_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	ClubId string `protobuf:"bytes,2,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
}

func (x *RoleExitClub_Req) Reset() {
	*x = RoleExitClub_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleExitClub_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleExitClub_Req) ProtoMessage() {}

func (x *RoleExitClub_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleExitClub_Req.ProtoReflect.Descriptor instead.
func (*RoleExitClub_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{10, 0}
}

func (x *RoleExitClub_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleExitClub_Req) GetClubId() string {
	if x != nil {
		return x.ClubId
	}
	return ""
}

type RoleExitClub_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleExitClub_Rsp) Reset() {
	*x = RoleExitClub_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleExitClub_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleExitClub_Rsp) ProtoMessage() {}

func (x *RoleExitClub_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleExitClub_Rsp.ProtoReflect.Descriptor instead.
func (*RoleExitClub_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{10, 1}
}

type RoleCancelClub_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	ClubId string `protobuf:"bytes,2,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
}

func (x *RoleCancelClub_Req) Reset() {
	*x = RoleCancelClub_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleCancelClub_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCancelClub_Req) ProtoMessage() {}

func (x *RoleCancelClub_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCancelClub_Req.ProtoReflect.Descriptor instead.
func (*RoleCancelClub_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{11, 0}
}

func (x *RoleCancelClub_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleCancelClub_Req) GetClubId() string {
	if x != nil {
		return x.ClubId
	}
	return ""
}

type RoleCancelClub_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleCancelClub_Rsp) Reset() {
	*x = RoleCancelClub_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleCancelClub_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCancelClub_Rsp) ProtoMessage() {}

func (x *RoleCancelClub_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCancelClub_Rsp.ProtoReflect.Descriptor instead.
func (*RoleCancelClub_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{11, 1}
}

type RoleRecvChannel_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId  string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *RoleRecvChannel_Req) Reset() {
	*x = RoleRecvChannel_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleRecvChannel_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRecvChannel_Req) ProtoMessage() {}

func (x *RoleRecvChannel_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRecvChannel_Req.ProtoReflect.Descriptor instead.
func (*RoleRecvChannel_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{12, 0}
}

func (x *RoleRecvChannel_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleRecvChannel_Req) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RoleRecvChannel_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleRecvChannel_Rsp) Reset() {
	*x = RoleRecvChannel_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleRecvChannel_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRecvChannel_Rsp) ProtoMessage() {}

func (x *RoleRecvChannel_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRecvChannel_Rsp.ProtoReflect.Descriptor instead.
func (*RoleRecvChannel_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{12, 1}
}

type RoleKick_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *RoleKick_Req) Reset() {
	*x = RoleKick_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleKick_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleKick_Req) ProtoMessage() {}

func (x *RoleKick_Req) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleKick_Req.ProtoReflect.Descriptor instead.
func (*RoleKick_Req) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{13, 0}
}

func (x *RoleKick_Req) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type RoleKick_Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *RoleKick_Rsp) Reset() {
	*x = RoleKick_Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[41]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleKick_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleKick_Rsp) ProtoMessage() {}

func (x *RoleKick_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[41]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleKick_Rsp.ProtoReflect.Descriptor instead.
func (*RoleKick_Rsp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{13, 1}
}

func (x *RoleKick_Rsp) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_role_proto protoreflect.FileDescriptor

var file_role_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x01,
	0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x1d, 0x0a, 0x03, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x5f, 0x0a, 0x03, 0x52, 0x73,
	0x70, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42,
	0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x6c, 0x75, 0x62,
	0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x52,
	0x0a, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x3a, 0x12, 0xca, 0xf3, 0x18,
	0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22,
	0xa1, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x1d, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x5f,
	0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x44, 0x42, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x12, 0x31, 0x0a, 0x0a,
	0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c,
	0x65, 0x44, 0x42, 0x52, 0x0a, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x3a,
	0x12, 0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18,
	0x02, 0x20, 0x01, 0x22, 0x91, 0x01, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x37, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x1a,
	0x32, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x3a, 0x12, 0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x91, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65,
	0x50, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x1a, 0x37, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70,
	0x1a, 0x35, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x50,
	0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x09, 0x52, 0x6f,
	0x6c, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x3a, 0x12, 0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x65, 0x0a, 0x0f, 0x52,
	0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x37,
	0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x3a, 0x12,
	0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02,
	0x20, 0x01, 0x22, 0x82, 0x01, 0x0a, 0x13, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c,
	0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x1d, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x38, 0x0a, 0x03, 0x52, 0x73, 0x70,
	0x12, 0x31, 0x0a, 0x0a, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75,
	0x62, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x42, 0x52, 0x0a, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c,
	0x65, 0x44, 0x42, 0x3a, 0x12, 0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x74, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x1d, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x2e, 0x0a, 0x03, 0x52, 0x73, 0x70,
	0x12, 0x27, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x62, 0x44, 0x42, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x44, 0x42,
	0x52, 0x07, 0x43, 0x6c, 0x75, 0x62, 0x44, 0x42, 0x73, 0x3a, 0x12, 0xca, 0xf3, 0x18, 0x08, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x8a, 0x01,
	0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x35, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x1a, 0x2c, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x12,
	0x25, 0x0a, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x44, 0x42, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x44, 0x42, 0x52, 0x06,
	0x43, 0x6c, 0x75, 0x62, 0x44, 0x42, 0x3a, 0x12, 0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x62, 0x0a, 0x0e, 0x52, 0x6f,
	0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x62, 0x1a, 0x1d, 0x0a, 0x03,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x1d, 0x0a, 0x03, 0x52,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x3a, 0x12, 0xca, 0xf3, 0x18, 0x08,
	0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x60,
	0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x62, 0x1a, 0x35,
	0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43,
	0x6c, 0x75, 0x62, 0x49, 0x64, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x3a, 0x12, 0xca, 0xf3,
	0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02, 0x20, 0x01,
	0x22, 0x60, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6c, 0x75, 0x62,
	0x1a, 0x35, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x3a, 0x12,
	0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0xca, 0xf3, 0x18, 0x02,
	0x20, 0x01, 0x22, 0x62, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x43, 0x6c, 0x75, 0x62, 0x1a, 0x35, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x1a, 0x05, 0x0a, 0x03, 0x52,
	0x73, 0x70, 0x3a, 0x12, 0xca, 0xf3, 0x18, 0x08, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0xca, 0xf3, 0x18, 0x02, 0x20, 0x01, 0x22, 0x59, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x63, 0x76, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x37, 0x0a, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x73, 0x70, 0x3a, 0x06, 0xca, 0xf3, 0x18, 0x02, 0x0a,
	0x00, 0x22, 0x52, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x1a, 0x1d, 0x0a,
	0x03, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x1f, 0x0a, 0x03,
	0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x3a, 0x06, 0xca,
	0xf3, 0x18, 0x02, 0x0a, 0x00, 0x32, 0xd4, 0x06, 0x0a, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x65,
	0x72, 0x12, 0x37, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x2e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0b, 0x52, 0x6f,
	0x6c, 0x65, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0e, 0x52, 0x6f, 0x6c,
	0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x73,
	0x70, 0x12, 0x3d, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70,
	0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x55, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x2e, 0x52, 0x73, 0x70,
	0x12, 0x49, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x1a,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x0f, 0x52,
	0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c,
	0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65,
	0x74, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x69, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x73,
	0x70, 0x12, 0x55, 0x0a, 0x13, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x62, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x62, 0x2e, 0x52, 0x73, 0x70,
	0x12, 0x40, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x62,
	0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4a, 0x6f, 0x69,
	0x6e, 0x43, 0x6c, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x62, 0x2e, 0x52,
	0x73, 0x70, 0x12, 0x40, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6c,
	0x75, 0x62, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x45,
	0x78, 0x69, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6c, 0x75, 0x62,
	0x2e, 0x52, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x43, 0x6c, 0x75, 0x62, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6c, 0x75, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6c, 0x75, 0x62, 0x2e, 0x52, 0x73, 0x70, 0x32, 0x90, 0x01, 0x0a,
	0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x12, 0x49,
	0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x76, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x63, 0x76, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x76, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x08, 0x52, 0x6f, 0x6c,
	0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x2e, 0x52, 0x73, 0x70, 0x42,
	0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData = file_role_proto_rawDesc
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_role_proto_rawDescData)
	})
	return file_role_proto_rawDescData
}

var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_role_proto_goTypes = []interface{}{
	(*RoleLogin)(nil),               // 0: proto.RoleLogin
	(*RoleGetInfo)(nil),             // 1: proto.RoleGetInfo
	(*RoleModifyName)(nil),          // 2: proto.RoleModifyName
	(*RolePowerUp)(nil),             // 3: proto.RolePowerUp
	(*RolePostChannel)(nil),         // 4: proto.RolePostChannel
	(*RoleGetClubRoleInfo)(nil),     // 5: proto.RoleGetClubRoleInfo
	(*RoleGetClubList)(nil),         // 6: proto.RoleGetClubList
	(*RoleGetClubInfo)(nil),         // 7: proto.RoleGetClubInfo
	(*RoleCreateClub)(nil),          // 8: proto.RoleCreateClub
	(*RoleJoinClub)(nil),            // 9: proto.RoleJoinClub
	(*RoleExitClub)(nil),            // 10: proto.RoleExitClub
	(*RoleCancelClub)(nil),          // 11: proto.RoleCancelClub
	(*RoleRecvChannel)(nil),         // 12: proto.RoleRecvChannel
	(*RoleKick)(nil),                // 13: proto.RoleKick
	(*RoleLogin_Req)(nil),           // 14: proto.RoleLogin.Req
	(*RoleLogin_Rsp)(nil),           // 15: proto.RoleLogin.Rsp
	(*RoleGetInfo_Req)(nil),         // 16: proto.RoleGetInfo.Req
	(*RoleGetInfo_Rsp)(nil),         // 17: proto.RoleGetInfo.Rsp
	(*RoleModifyName_Req)(nil),      // 18: proto.RoleModifyName.Req
	(*RoleModifyName_Rsp)(nil),      // 19: proto.RoleModifyName.Rsp
	(*RolePowerUp_Req)(nil),         // 20: proto.RolePowerUp.Req
	(*RolePowerUp_Rsp)(nil),         // 21: proto.RolePowerUp.Rsp
	(*RolePostChannel_Req)(nil),     // 22: proto.RolePostChannel.Req
	(*RolePostChannel_Rsp)(nil),     // 23: proto.RolePostChannel.Rsp
	(*RoleGetClubRoleInfo_Req)(nil), // 24: proto.RoleGetClubRoleInfo.Req
	(*RoleGetClubRoleInfo_Rsp)(nil), // 25: proto.RoleGetClubRoleInfo.Rsp
	(*RoleGetClubList_Req)(nil),     // 26: proto.RoleGetClubList.Req
	(*RoleGetClubList_Rsp)(nil),     // 27: proto.RoleGetClubList.Rsp
	(*RoleGetClubInfo_Req)(nil),     // 28: proto.RoleGetClubInfo.Req
	(*RoleGetClubInfo_Rsp)(nil),     // 29: proto.RoleGetClubInfo.Rsp
	(*RoleCreateClub_Req)(nil),      // 30: proto.RoleCreateClub.Req
	(*RoleCreateClub_Rsp)(nil),      // 31: proto.RoleCreateClub.Rsp
	(*RoleJoinClub_Req)(nil),        // 32: proto.RoleJoinClub.Req
	(*RoleJoinClub_Rsp)(nil),        // 33: proto.RoleJoinClub.Rsp
	(*RoleExitClub_Req)(nil),        // 34: proto.RoleExitClub.Req
	(*RoleExitClub_Rsp)(nil),        // 35: proto.RoleExitClub.Rsp
	(*RoleCancelClub_Req)(nil),      // 36: proto.RoleCancelClub.Req
	(*RoleCancelClub_Rsp)(nil),      // 37: proto.RoleCancelClub.Rsp
	(*RoleRecvChannel_Req)(nil),     // 38: proto.RoleRecvChannel.Req
	(*RoleRecvChannel_Rsp)(nil),     // 39: proto.RoleRecvChannel.Rsp
	(*RoleKick_Req)(nil),            // 40: proto.RoleKick.Req
	(*RoleKick_Rsp)(nil),            // 41: proto.RoleKick.Rsp
	(*RoleDB)(nil),                  // 42: proto.RoleDB
	(*ClubRoleDB)(nil),              // 43: proto.ClubRoleDB
	(*RoleName)(nil),                // 44: proto.RoleName
	(*RolePower)(nil),               // 45: proto.RolePower
	(*ClubDB)(nil),                  // 46: proto.ClubDB
}
var file_role_proto_depIdxs = []int32{
	42, // 0: proto.RoleLogin.Rsp.RoleDB:type_name -> proto.RoleDB
	43, // 1: proto.RoleLogin.Rsp.ClubRoleDB:type_name -> proto.ClubRoleDB
	42, // 2: proto.RoleGetInfo.Rsp.RoleDB:type_name -> proto.RoleDB
	43, // 3: proto.RoleGetInfo.Rsp.ClubRoleDB:type_name -> proto.ClubRoleDB
	44, // 4: proto.RoleModifyName.Rsp.RoleName:type_name -> proto.RoleName
	45, // 5: proto.RolePowerUp.Rsp.RolePower:type_name -> proto.RolePower
	43, // 6: proto.RoleGetClubRoleInfo.Rsp.ClubRoleDB:type_name -> proto.ClubRoleDB
	46, // 7: proto.RoleGetClubList.Rsp.ClubDBs:type_name -> proto.ClubDB
	46, // 8: proto.RoleGetClubInfo.Rsp.ClubDB:type_name -> proto.ClubDB
	14, // 9: proto.RoleSer.RoleLogin:input_type -> proto.RoleLogin.Req
	16, // 10: proto.RoleSer.RoleGetInfo:input_type -> proto.RoleGetInfo.Req
	18, // 11: proto.RoleSer.RoleModifyName:input_type -> proto.RoleModifyName.Req
	20, // 12: proto.RoleSer.RolePowerUp:input_type -> proto.RolePowerUp.Req
	22, // 13: proto.RoleSer.RolePostChannel:input_type -> proto.RolePostChannel.Req
	28, // 14: proto.RoleSer.RoleGetClubInfo:input_type -> proto.RoleGetClubInfo.Req
	26, // 15: proto.RoleSer.RoleGetClubList:input_type -> proto.RoleGetClubList.Req
	24, // 16: proto.RoleSer.RoleGetClubRoleInfo:input_type -> proto.RoleGetClubRoleInfo.Req
	30, // 17: proto.RoleSer.RoleCreateClub:input_type -> proto.RoleCreateClub.Req
	32, // 18: proto.RoleSer.RoleJoinClub:input_type -> proto.RoleJoinClub.Req
	34, // 19: proto.RoleSer.RoleExitClub:input_type -> proto.RoleExitClub.Req
	36, // 20: proto.RoleSer.RoleCancelClub:input_type -> proto.RoleCancelClub.Req
	38, // 21: proto.RoleDaemonSer.RoleRecvChannel:input_type -> proto.RoleRecvChannel.Req
	40, // 22: proto.RoleDaemonSer.RoleKick:input_type -> proto.RoleKick.Req
	15, // 23: proto.RoleSer.RoleLogin:output_type -> proto.RoleLogin.Rsp
	17, // 24: proto.RoleSer.RoleGetInfo:output_type -> proto.RoleGetInfo.Rsp
	19, // 25: proto.RoleSer.RoleModifyName:output_type -> proto.RoleModifyName.Rsp
	21, // 26: proto.RoleSer.RolePowerUp:output_type -> proto.RolePowerUp.Rsp
	23, // 27: proto.RoleSer.RolePostChannel:output_type -> proto.RolePostChannel.Rsp
	29, // 28: proto.RoleSer.RoleGetClubInfo:output_type -> proto.RoleGetClubInfo.Rsp
	27, // 29: proto.RoleSer.RoleGetClubList:output_type -> proto.RoleGetClubList.Rsp
	25, // 30: proto.RoleSer.RoleGetClubRoleInfo:output_type -> proto.RoleGetClubRoleInfo.Rsp
	31, // 31: proto.RoleSer.RoleCreateClub:output_type -> proto.RoleCreateClub.Rsp
	33, // 32: proto.RoleSer.RoleJoinClub:output_type -> proto.RoleJoinClub.Rsp
	35, // 33: proto.RoleSer.RoleExitClub:output_type -> proto.RoleExitClub.Rsp
	37, // 34: proto.RoleSer.RoleCancelClub:output_type -> proto.RoleCancelClub.Rsp
	39, // 35: proto.RoleDaemonSer.RoleRecvChannel:output_type -> proto.RoleRecvChannel.Rsp
	41, // 36: proto.RoleDaemonSer.RoleKick:output_type -> proto.RoleKick.Rsp
	23, // [23:37] is the sub-list for method output_type
	9,  // [9:23] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	file_com_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleModifyName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePowerUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePostChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubRoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleCreateClub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleJoinClub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleExitClub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleCancelClub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleRecvChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleLogin_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleLogin_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetInfo_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetInfo_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleModifyName_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleModifyName_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePowerUp_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePowerUp_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePostChannel_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePostChannel_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubRoleInfo_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubRoleInfo_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubList_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubList_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubInfo_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleGetClubInfo_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleCreateClub_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleCreateClub_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleJoinClub_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleJoinClub_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleExitClub_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleExitClub_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleCancelClub_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleCancelClub_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleRecvChannel_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleRecvChannel_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[40].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleKick_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[41].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleKick_Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_rawDesc = nil
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
