[Transport]
Host = "{{Transport_Host}}"
Port = 40001
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "{{Router_Consul_Consul_Host}}"

[[Plugin.Broker.broker_nats]]
URL = "{{Broker_Nats_URL}}"

[[Plugin.Gate.gate_grpc]]
Port = 40003

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.Metric.metric_prom]]
Port = 40002


[App]
PrePareTime = 10 # 启动前准备时长