[Transport]
Host = "{{Transport_Host}}"
Port = 40001
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "{{Router_Consul_Consul_Host}}"

[[Plugin.Broker.broker_nats]]
URL = "{{Broker_Nats_URL}}"

[[Plugin.Log.log_zap]]
LogLevel = "INFO "
Encoding = "console"

[[Plugin.DB.db_mongo]]
URI = "{{DB_Mongo_DB}}"
DataBase = "uiddb"

[[Plugin.Lease.lease_etcd]]
Endpoints = "{{Lease_Etcd_Endpoints}}"
DialTimeout = 5
LeaseKeepLiveTime = 10
PreExitTime = 5

[[Plugin.Metric.metric_prom]]
Port = 40002

[App]
PrePareTime = 10 # 启动前准备时长
CachePoolSize = 10000 # 缓存池
VoteLease = "/single/uidapp"