apiVersion: v1
kind: Service
metadata:
  namespace: m3demobase
  name: consul
  labels:
    app: consul
spec:
  type: ClusterIP
  ports:
    - name: tcp-8500-8500
      port: 8500
      protocol: TCP
      targetPort: 8500
  selector:
    app: consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: consul
  name: consul
  namespace: m3demobase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consul
    spec:
      containers:
        - image: consul
          imagePullPolicy: Always
          name: consul
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          args:
            - "agent"
            - "-server"
            - "-bootstrap"
            - "-ui"
            - "-node=1"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
            - "-advertise=$(PODIP)"
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always
