apiVersion: v1
kind: Service
metadata:
  namespace: m3demobase
  name: etcd
  labels:
    app: etcd
spec:
  type: ClusterIP
  ports:
    - name: tcp-2379-2379
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: tcp-2380-2380
      port: 2380
      protocol: TCP
      targetPort: 2380
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: etcd
  name: etcd
  namespace: m3demobase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: etcd
    spec:
      containers:
        - image: bitnami/etcd
          imagePullPolicy: Always
          name: etcd
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://etcd.m3demobase.svc.cluster.local:2379
      restartPolicy: Always
