apiVersion: v1
kind: Service
metadata:
  namespace: m3demo
  name: mongo
  labels:
    app: mongo
spec:
  type: ClusterIP
  ports:
  - name: tcp-27017-27017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: mongo
  name: mongo
  namespace: m3demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - image: docker.io/mongo
        imagePullPolicy: Always
        name: mongodb
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
