---
apiVersion: v1
kind: Service
metadata:
  namespace: m3demobase
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - name: elasticsearch
      nodePort: 30006
      port: 30006
      protocol: TCP
      targetPort: 30006
    - name: consul
      nodePort: 30007
      port: 30007
      protocol: TCP
      targetPort: 30007
    - name: logstash
      nodePort: 30008
      port: 30008
      protocol: TCP
      targetPort: 30008
    - name: kibana
      nodePort: 30009
      port: 30009
      protocol: TCP
      targetPort: 30009
    - name: jaeger-query
      nodePort: 30010
      port: 30010
      protocol: TCP
      targetPort: 30010
    - name: prometheus
      nodePort: 30011
      port: 30011
      protocol: TCP
      targetPort: 30011
    - name: grafana
      nodePort: 30012
      port: 30012
      protocol: TCP
      targetPort: 30012
  selector:
    app: nginx
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-passwd
  namespace: m3demobase
data:
  nginx.passwd: |-                
        admin:$apr1$gd8bjt9E$ssWO7ruD4CxJ0u1Yij55p.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: m3demobase
data:
  nginx.conf: |-                
        user  root;
        worker_processes  1;
        error_log  /var/log/nginx/error.log warn;
        pid        /var/run/nginx.pid;
        events {
                worker_connections  1024;
        }
        http {
          include       mime.types;
          default_type  application/octet-stream;

          server {
            listen 30006;
            auth_basic "Please input password elasticsearch";
            auth_basic_user_file /etc/nginx/nginx.passwd;
            location / {
              proxy_pass http://elasticsearch.m3demobase.svc.cluster.local:9200/;
            }
          }
          server {
            listen 30007;
            auth_basic "Please input password consul";
            auth_basic_user_file /etc/nginx/nginx.passwd;
            location / {
              proxy_pass http://consul.m3demobase.svc.cluster.local:8500/;
            }
          }
          server {
            listen 30008;
            auth_basic "Please input password logstash";
            auth_basic_user_file /etc/nginx/nginx.passwd;
            location / {
              proxy_pass http://logstash.m3demobase.svc.cluster.local:9600/;
            }
          }
          server {
            listen 30009;
            auth_basic "Please input password kibana";
            auth_basic_user_file /etc/nginx/nginx.passwd;
            location / {
              proxy_pass http://kibana.m3demobase.svc.cluster.local:5601/;
            }
          }
          server {
            listen 30010;
            auth_basic "Please input password jaeger-query";
            auth_basic_user_file /etc/nginx/nginx.passwd;
            location / {
              proxy_pass http://jaeger-query.m3demobase.svc.cluster.local:16686/;
            }
          }
          server {
            listen 30011;
            auth_basic "Please input password prometheus";
            auth_basic_user_file /etc/nginx/nginx.passwd;
            location / {
              proxy_pass http://prometheus.m3demobase.svc.cluster.local:9090/;
            }
          }
          server {
            listen 30012;
            location / {
              proxy_set_header Host $http_host;
              proxy_pass http://grafana.m3demobase.svc.cluster.local:3000/;
            }
          }
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: m3demobase
  labels: 
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: nginx
  template:
    metadata:
      labels: 
        app: nginx
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-passwd
          mountPath: /etc/nginx/nginx.passwd
          subPath: nginx.passwd
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: nginx-conf
        configMap:
          defaultMode: 0640
          name: nginx-conf
      - name: nginx-passwd
        configMap:
          defaultMode: 0640
          name: nginx-passwd
