apiVersion: v1
kind: Service
metadata:
  namespace: m3demo
  name: gateapp-out
  labels:
    app: gateapp-out
spec:
  type: NodePort
  ports:
    - name: grpc
      nodePort: 30006
      port: 40003
      protocol: TCP
      targetPort: 40003
  selector:
    app: gateapp
---
apiVersion: v1
kind: Service
metadata:
  namespace: m3demo
  name: consul-out
  labels:
    app: consul-out
spec:
  type: NodePort
  ports:
    - name: tcp
      nodePort: 30005
      port: 8500
      protocol: TCP
      targetPort: 8500
  selector:
    app: consul