apiVersion: v1
kind: Service
metadata:
  namespace: m3demo
  name: gateapp
  labels:
    app: gateapp
spec:
  type: ClusterIP
  ports:
    - name: tcp-40001-40001
      port: 40001
      protocol: TCP
      targetPort: 40001
    - name: tcp-40002-40002
      port: 40002
      protocol: TCP
      targetPort: 40002
    - name: tcp-40003-40003
      port: 40003
      protocol: TCP
      targetPort: 40003
  selector:
    app: gateapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: gateapp
  name: gateapp
  namespace: m3demo
spec:
  serviceName: ""
  replicas: 1
  selector:
    matchLabels:
      app: gateapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateapp
    spec:
      containers:
        - image: {{ .Values.m3demoimage }}
          imagePullPolicy: Always
          name: gateapp
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          workingDir: /go/bin/demo/deploy
          command:
          - sh
          - start.sh
          - k8s
          - world1
          - gate
          - $(ENV_M3DEMO_Ins)
          env:
            - name: ENV_M3DEMO_Ins
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENV_M3DEMO_Transport_Host
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV_M3DEMO_Transport_Host
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV_M3DEMO_Router_Consul_Consul_Host
              value: consul:8500
            - name: ENV_M3DEMO_Broker_Nats_URL
              value: nats:4222
            - name: ENV_M3DEMO_DB_Mongo_DB
              value: mongodb://mongo:27017
            - name: ENV_M3DEMO_Lease_Etcd_Endpoints
              value: etcd:2379
      restartPolicy: Always
