[Transport]
Host = "{{Transport_Host}}"
Port = 40001
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "{{Router_Consul_Consul_Host}}"

[[Plugin.Broker.broker_nats]]
URL = "{{Broker_Nats_URL}}"

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.DB.db_mongo]]
URI = "{{DB_Mongo_DB}}"
DataBase = "roledb"

[[Plugin.Metric.metric_prom]]
Port = 40002

[Server]
[[Server.Actor]]
ActiveTimeOut = 60  # role 存活时间
SaveTimeInter = 10  # role自动存储时间
TickTimeInter = 10  # 定时器轮转时间
MaxReqChanSize = 10 # 最大接受信道
MaxReqWaitTime = 30 # 最大等待时间
AutoCreate = 1 # 自动创建Actor
LeaseMode = 0   # 启用租约管理
LeasePrefix = "1"   # 租约前缀
AllocLeaseTimeOut = 1    # 申请租约超时时间
WaitFreeLeaseTimeOut = 1  # 预估数据迁出时长

LuaFile = "../../resource/roleser.lua"
[App]
PrePareTime = 10 # 启动前准备时长