[Transport]
Host = "127.0.0.1"
Port = 32510
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"
AliveHost = "127.0.0.1"
AlivePort = 32513

[[Plugin.Broker.broker_nats]]
URL = "127.0.0.1:4222"

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.DB.db_mongo]]
URI = "mongodb://admin:123456@127.0.0.1:27017"
DataBase = "clubdb"

[[Plugin.Metric.metric_prom]]
Host = "127.0.0.1"
Port = 32511

[[Plugin.Trace.trace_jaeger]]
Host = "127.0.0.1"

# [[Plugin.Trans.trans_http2]]
# Host = "127.0.0.1"
# Port = 32510

[[Plugin.Trans.trans_nats]]
URL = "127.0.0.1:4222"

[App]
PrePareTime = 10 # 启动前准备时长