
[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"
AliveHost = "127.0.0.1"
AlivePort = 32413

[[Plugin.Broker.broker_nats]]
URL = "127.0.0.1:4222"

[[Plugin.Gate.gate_grpc]]
Port = 32412

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.Metric.metric_prom]]
Host = "127.0.0.1"
Port = 32411
ConsulHost = "127.0.0.1:8500"
ConsulSvc = "M3Demo_Metric"
ConsulAppPrefix = "Metric"


# [[Plugin.Trans.trans_http2]]
# Host = "127.0.0.1"
# Port = 32410

[[Plugin.Trans.trans_nats]]
URL = "127.0.0.1:4222"

[App]
PrePareTime = 10 # 启动前准备时长