[Transport]
Host = "127.0.0.1"
Port = 32420
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
URL = "127.0.0.1:4222"

[[Plugin.Gate.gate_grpc]]
Port = 32422

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.Metric.metric_prom]]
Port = 32421

[[Plugin.Trace.trace_jaeger]]
Host = "127.0.0.1"

[App]
PrePareTime = 10 # 启动前准备时长