[Transport]
Host = "127.0.0.1"
Port = 32410
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
URL = "127.0.0.1:4222"

[[Plugin.Gate.gate_grpc]]
Port = 32412

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.Metric.metric_prom]]
Port = 32411
ConsulHost = "127.0.0.1:8500"
ConsulSvc = "M3Demo_Metric"
ConsulAppPrefix = "Metric"


[App]
PrePareTime = 10 # 启动前准备时长