[App]
[Transport]
Addr = "127.0.0.1:22102"
BroadTimeOut = 5

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"
[[Plugin.Broker.broker_nats]]
NatsURL = "127.0.0.1:4222"

[Resource]
CfgPath = "../../resource"