[Transport]
Addr = "127.0.0.1:32202"
BroadTimeOut = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
NatsURL = "127.0.0.1:4222"

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.DB.db_redis]]
Host = "127.0.0.1"
Port = 6379
Auth = "123456"
MaxIdle = 100
MaxActive = 100

[[Plugin.Lease.lease_etcd]]
Endpoints = "127.0.0.1:2379"
DialTimeout = 5
LeaseKeepLiveTime = 10
PreExitTime = 5

[App]
PrePareTime = 10 # 启动前准备时长
CachePoolSize = 10000 # 缓存池
VoteLease = "/single/onlineapp"
AppAliveTimeOut = 10    # 