[Transport]
Addr = "127.0.0.1:32301"
BroadTimeOut = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
NatsURL = "127.0.0.1:4222"

[[Plugin.Log.log_zap]]
LogLevel = "INFO "
Encoding = "console"

[[Plugin.DB.db_redis]]
Host = "127.0.0.1"
Port = 6379
Auth = "123456"
MaxIdle = 100
MaxActive = 100

[Server]
[[Server.Actor]]
ActiveTimeOut = 60  # role 存活时间
SaveTimeInter = 10  # role自动存储时间
TickTimeInter = 10  # 定时器轮转时间
MaxReqChanSize = 10 # 最大接受信道
MaxReqWaitTime = 30 # 最大等待时间
LeaseMode = 0   # 启用租约管理

[App]
PrePareTime = 10 # 启动前准备时长