[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"
AliveHost = "127.0.0.1"
AlivePort = 32123

[[Plugin.Broker.broker_nats]]
URL = "127.0.0.1:4222"

[[Plugin.Log.log_zap]]
LogLevel = "INFO "
Encoding = "console"

[[Plugin.DB.db_mongo]]
URI = "mongodb://admin:123456@127.0.0.1:27017"
DataBase = "uiddb"

[[Plugin.Lease.lease_etcd]]
Endpoints = "127.0.0.1:2379"
DialTimeout = 5
LeaseKeepLiveTime = 10
PreExitTime = 5

[[Plugin.Metric.metric_prom]]
Host = "127.0.0.1"
Port = 32121

[[Plugin.Trace.trace_jaeger]]
Host = "127.0.0.1"

# [[Plugin.Trans.trans_tcp]]
# Host = "127.0.0.1"
# Port = 32120

[[Plugin.Trans.trans_nats]]
URL = "127.0.0.1:4222"

[App]
PrePareTime = 10 # 启动前准备时长
CachePoolSize = 10000 # 缓存池
VoteLease = "/single/uidapp"