[Transport]
Addr = "127.0.0.1:32101"
BroadcastTimeout = 5

[Options]
[[Options.Mesh]]
WatcherInterSecond = 1
[[Options.Resource]]
CfgPath = "../../resource"
[[Options.Shape]]
RuleConfigFile = "../../resource/rules.toml"

[Plugin]
[[Plugin.Router.router_consul]]
ConsulHost = "127.0.0.1:8500"

[[Plugin.Broker.broker_nats]]
URL = "127.0.0.1:4222"

[[Plugin.Log.log_zap]]
LogLevel = "DEBUG"
Encoding = "console"

[[Plugin.DB.db_mongo]]
URI = "mongodb://admin:123456@127.0.0.1:27017"
DataBase = "uiddb"

[[Plugin.Lease.lease_etcd]]
Endpoints = "127.0.0.1:2379"
DialTimeout = 5
LeaseKeepLiveTime = 10
PreExitTime = 5

[App]
PrePareTime = 10 # 启动前准备时长
CachePoolSize = 10000 # 缓存池
VoteLease = "/single/uidapp"